FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y automake autoconf libtool g++ wget tar git gzip unzip make cmake software-properties-common curl

ADD . /repo
WORKDIR /repo
RUN autoreconf -i -W all
RUN ./configure
RUN make -j8
